// <auto-generated />
namespace EmployeeTrainingManagement.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class project_designation_EmployeeProjectDetailstabl : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(project_designation_EmployeeProjectDetailstabl));
        
        string IMigrationMetadata.Id
        {
            get { return "201906031049049_project_designation_EmployeeProjectDetailstabl"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
